mex -g -I../../tools/lua/include       ...
  sugarmex.c mexhandle.c meshmex.c varsmex.c assemblemex.c netdrawmex.c  netoutmex.c netdrawmlab.c netoutmlab.c modelmatlab.c modelmf2wrap.c ...
  sugarlib.a ...
  ../../tools/lua/lib/liblua.a ...
  ../../tools/lua/lib/liblualib.a
